title: Blog
author: Devil
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My First Blog Page
  On GitHub Let's Go..

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima


